# Generated by Django 4.1.2 on 2022-10-22 17:23

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function),
        ),
        migrations.AddField(
            model_name='frontman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function),
        ),
    ]
